# Deeplearning

## Lession 1

### 11. Perceptron Algorithm

In [1]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    print(X)
    print(y)
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines


### 15. Discrete vs Continuous

#### QUIZ QUESTION
The sigmoid function is defined as sigmoid(x) = 1/(1+e-x). If the score is defined by 4x1 + 5x2 - 9 = score, then which of the following points has exactly a 50% probability of being blue or red? (Choose all that are correct.)

In [2]:
import math

points = [[1, 1], [2, 4], [5, -5], [-4, 5]]
sigmoid = lambda x: 1/(1 + math.exp(-x))

for x1, x2 in points:
    score = 4*x1 + 5*x2 - 9
    print("Point({},{}) Score: {}".format(x1, x2,score))
    print("Point({},{}) Sigmoid: {}".format(x1, x2, sigmoid(score)))

Point(1,1) Score: 0
Point(1,1) Sigmoid: 0.5
Point(2,4) Score: 19
Point(2,4) Sigmoid: 0.9999999943972036
Point(5,-5) Score: -14
Point(5,-5) Sigmoid: 8.315280276641321e-07
Point(-4,5) Score: 0
Point(-4,5) Sigmoid: 0.5


### 16.Softmax

#### QUESTION 1 OF 2
What function turns every number into a positive number?

In [3]:
import math
# Dim a = 1, b = 0, c = -1
a, b, c = 1, 0, -1

softmax = lambda x: math.exp(x)/ (math.exp(a) + math.exp(b) + math.exp(c))
Pa = softmax(a)
Pb = softmax(b)
Pc = softmax(c)

print(round(Pa, 2))
print(round(Pb, 2))
print(round(Pc,2))


0.67
0.24
0.09


> The answer is exp becuse the output of $e^x$ is always positive number.
$$ P(class i) = \frac{e^{Zi}}{e^{Z1} + ... + e^{Zn}} $$

#### Quiz: Coding Softmax
And now, your time to shine! Let's code the formula for the Softmax function in Python. 

In [4]:
import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax(L):
    eL = np.sum(np.exp(L))
    return [np.exp(i)/eL for i in L]

### 21. Cross-Entroy 2

Cross-Entropy=$-\sum_{i=1}^{m} y_iln(p_i)+ln(1-p_i)$

#### Quiz: Coding Cross-entropy
Now, time to shine! Let's code the formula for cross-entropy in Python.

In [5]:
import numpy as np

# Write a function that takes as input two lists Y, P,
# and returns the float corresponding to their cross-entropy.
def cross_entropy(Y, P):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))
    
Y = [1, 0, 1, 1]
P = [0.4, 0.6, 0.1, 0.5]
cross_entropy(Y, P)

4.828313737302301

### 22. Multi-Class Cross Entropy

Cross-Entropy= $-\sum_{i=1}^n\sum_{j=1}^myij \cdot ln(pij)$

### 23. Logistic Regressioon

Error Function = $-\frac{1}m \sum^m_{i=1} (1-y_i)(ln(1-\hat{y}_i)) + y_iln(\hat{y}_i)$

E(W,b) = $-\frac{1}{m} \sum^m_{i=1} (1-y_i)(ln(1-\sigma(Wx^{(i)}+b)) + y_iln(\sigma(Wx^{(i)}+b)$

### 32. Neural Network Architecture

QUESTION 1 OF 2
Based on the above video, let's define the combination of two new perceptrons as w1*0.4 + w2*0.6 + b. Which of the following values for the weights and the bias would result in the final probability of the point to be 0.88?

In [6]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

formula = lambda W1, W2, b: sigmoid(W1*0.4 + W2*0.6 + b)
print(formula(2, 6, -2))
print(formula(3, 5, -2.2))
print(formula(5, 4, -3))



0.9168273035060777
0.8807970779778823
0.8021838885585818


## Lession 2

### 4.Gradient Descent:The Code

$\Delta w_i = \eta \delta x_i$  
$\Delta w_i = learnrate * error\_term * x $
#### Error term $\delta$ as  
$\delta = (y - \hat{y})f'(h) = (y - \hat{y})f'(\sum w_ix_i)$



$ \hat{y} = \sigma(\sum{_i} w_ix_i)$  

$f'(\sum w_ix_i) = \hat{y} \cdot (1 - \hat{y}))$



ref: https://math.stackexchange.com/questions/78575/derivative-of-sigmoid-function-sigma-x-frac11e-x

In [7]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])

### Calculate one gradient descent step for each weight
### Note: Some steps have been consolidated, so there are
###       fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights
h = np.dot(x,w)
print("h = sum of the w_i * x_i", h);

# TODO: Calculate output of neural network
nn_output = sigmoid(h)
print("sigmoid the summation: ", nn_output)
# TODO: Calculate error of neural network
error = y - nn_output

# TODO: Calculate the error term
#       Remember, this requires the output gradient, which we haven't
#       specifically added a variable for.
error_term = error * sigmoid_prime(h)

# TODO: Calculate change in weights
del_w = learnrate * error_term * x

print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)

h = sum of the w_i * x_i 0.7999999999999998
sigmoid the summation:  0.6899744811276125
Neural Network output:
0.6899744811276125
Amount of Error:
-0.1899744811276125
Change in Weights:
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]


### 5.Implementing Gradient Descent


In [11]:
import numpy as np
from data_prep import features, targets, features_test, targets_test


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

# TODO: We haven't provided the sigmoid_prime function like we did in
#       the previous lesson to encourage you to come up with a more
#       efficient solution. If you need a hint, check out the comments
#       in solution.py from the previous lecture.

# Use to same seed to make debugging easier
np.random.seed(42)
#print(features)
#print(targets)
#print(features_test)
#print(targets_test)
n_records, n_features = features.shape
#print(n_records)
#print(n_features)
last_loss = None

# Initialize weights
weights = np.random.normal(scale=1 / n_features**.5, size=n_features)

# Neural Network hyperparameters
epochs = 1000
learnrate = 0.5

for e in range(epochs):
    del_w = np.zeros(weights.shape)
    for x, y in zip(features.values, targets):
        # Loop through all records, x is the input, y is the target

        # Note: We haven't included the h variable from the previous
        #       lesson. You can add it if you want, or you can calculate
        #       the h together with the output

        # TODO: Calculate the output
        output = sigmoid(np.dot(x,weights))

        # TODO: Calculate the error
        error = y - output

        # TODO: Calculate the error term
        error_term = error * output * (1 - output)
        # TODO: Calculate the change in weights for this sample
        #       and add it to the total weight change
        del_w += learnrate * x * error_term
    # TODO: Update weights using the learning rate and the average change in weights
    weights += learnrate * del_w / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        out = sigmoid(np.dot(features, weights))
        loss = np.mean((out - targets) ** 2)
        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss


# Calculate accuracy on test data
tes_out = sigmoid(np.dot(features_test, weights))
predictions = tes_out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))

Train loss:  0.2634711464098939
Train loss:  0.22351730609465992
Train loss:  0.20940833581363916
Train loss:  0.20359343681746
Train loss:  0.20087567293629532
Train loss:  0.19945113185302385
Train loss:  0.1986335569379286
Train loss:  0.19813048800765418
Train loss:  0.19780393857042008
Train loss:  0.19758300602502077
Prediction accuracy: 0.725


### 6. Multilayer Perceptrons


Matrix: 
first matrix row $\circ$ second matrix column

In [27]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network
# 4X3 matrix
print("weight in to hidden:",weights_input_to_hidden)
print("weight hidden to out",weights_hidden_to_output)

print("X:",X) # 4 elements
hidden_layer_in = np.dot(X, weights_input_to_hidden)
print(hidden_layer_in)
# active function
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

weight in to hidden: [[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]]
weight hidden to out [[-0.10128311  0.03142473]
 [-0.09080241 -0.14123037]
 [ 0.14656488 -0.02257763]]
X: [ 0.49671415 -0.1382643   0.64768854  1.52302986]
[-0.34365494 -0.29801368  0.00097362]
Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.49815196 0.48539772]


### 7.Backpropagation

#### Input  
$\begin{bmatrix} 0.5 & 0.1 & -0.2 \end{bmatrix}$
#### weights input to hidden
$\begin{bmatrix} 0.5 & -0.6 \\\\ 0.1 & -0.2 \\\\ 0.1 & 0.7 \end{bmatrix}$

#### weights output hidden to output
$\begin{bmatrix} 0.1 & -0.3 \end{bmatrix}$


#### Error to hidden unit 
$ \delta{_j} = (\sum{_k}W_{jk}\delta{_k})f'(h_j) $

#### Error Gradient descent steps - Hidden to output weight step
$ \Delta{W} = \eta \delta{^o}a $

####  Error Input to hidden weights $w_i$
$ \Delta{W_i} = \eta \delta{^h}x_i $

In [ ]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate output error
error = None

# TODO: Calculate error term for output layer
output_error_term = None

# TODO: Calculate error term for hidden layer
hidden_error_term = None

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = None

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = None

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)
